### PR TITLE
Cannot RestoreToPointInTime into specified subnets

### PR DESCRIPTION
**Pull request by mikey-**
Re-creating PR: #52 

Issue #, if available: #15 

Also see linked issue:
aws-cloudformation/aws-cloudformation-coverage-roadmap#336

Description of changes:
This occurs as the dbSubnetGroupName field isn't included in translator function: restoreDbClusterToPointInTimeRequest.
The appropriate course of action here is to simply add the missing field.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Thanks for your patience

### CODE REVIEW

**Comment by mikey-** [comment]
@osdrv @ammokhov :^) here it is again, in all it's gory glory :)

**Review by osdrv — APPROVED** [review]

**Comment by osdrv** [comment]
@mikey- Thanks once again, great job! @ammokhov I'm good here, please check it once you have a spare moment.

**Comment by mikey-** [comment]
@osdrv you're very welcome, this was really satisfying for me :) 

Thank you and @ammokhov for making it a great experience. Looking forward to making more contributions :)

**Comment by mikey-** [comment]
📲  @ammokhov !  Press the ✅  button (please) :)

**Comment by mikey-** [comment]
@osdrv do you know if there is there anyone else that can approve this change?

**Review by mikey- — COMMENTED** [review]
@ammokhov @osdrv Sorry, to bother you both, but this is some very low hanging fruit just waiting to be picked :)

**Comment by osdrv** [comment]
@mikey- apologies for a late response, the change has been merged now.

A quick remark on the further change progression: a change landing in this repo means that one can immediately build and register a custom resource handler using CFN registry (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/registry.html). On the other hand, it will take a while to get it deployed and made a part of the default handler. In other words, no ETA on getting this change rolled out globally yet.

**Comment by mikey-** [comment]
Thank you so much @moataz-mhmd for the approval
Thank you so much @ammokhov for the quick response, support on the CodeBuild process & initial approval 
Thank you so much @osdrv for your approval, migrating the build process to GH actions and for clarifying the process :)

**Pull request merged**
